import 'dotenv/config';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StreamableHTTPClientTransport } from '@modelcontextprotocol/sdk/client/streamableHttp.js';
import { Sandbox } from 'e2b';
import { CallToolResultSchema } from '@modelcontextprotocol/sdk/types.js';

// --- 1. THE NEW CLEANER FUNCTION ---
// This strips out the JSON garbage and finds the actual human text.
function cleanText(input: any): string {
  let text = typeof input === 'string' ? input : JSON.stringify(input);
  
  // 1. Try to parse if it's a JSON string
  try {
    const parsed = JSON.parse(text);
    // If it's an Exa result structure
    if (parsed.results && Array.isArray(parsed.results)) {
        return parsed.results.map((r: any) => r.text || r.summary).join('\n\n');
    }
    // If it's a Perplexity structure
    if (parsed.content && Array.isArray(parsed.content)) {
        return parsed.content.map((c: any) => c.text).join('\n\n');
    }
    // If it's a direct text field
    if (parsed.text) return parsed.text;
  } catch (e) {
    // Not JSON, keep going
  }

  // 2. Remove Markdown Images/Links that clutter
  text = text.replace(/!\[.*?\]\(.*?\)/g, ''); // remove images
  text = text.replace(/<think>[\s\S]*?<\/think>/g, ''); // remove internal thoughts

  // 3. Extract the "Meat"
  // If we see "text": "...", extract just that part
  const textMatch = text.match(/"text":\s*"([^"]+)"/);
  if (textMatch) return textMatch[1].replace(/\\n/g, '\n');

  return text.substring(0, 500); // Fallback
}

// --- 2. THE NEW SEXY EMAIL TEMPLATE ---
// "Professional Brief" Style - Minimalist, Serif fonts, Reading focus.
function generateHumanReport(company: string, findings: any[]): string {
  const date = new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });
  
  return `
<!DOCTYPE html>
<html>
<head>
<style>
  body { font-family: 'Georgia', serif; color: #111; max-width: 680px; margin: 0 auto; padding: 40px 20px; line-height: 1.6; background: #fff; }
  .header { border-bottom: 2px solid #000; padding-bottom: 20px; margin-bottom: 40px; }
  .brand { font-family: 'Helvetica Neue', sans-serif; font-weight: 900; letter-spacing: 1px; font-size: 14px; color: #666; text-transform: uppercase; }
  .title { font-size: 32px; font-weight: 700; margin: 10px 0 5px 0; letter-spacing: -0.5px; }
  .meta { font-family: 'Helvetica Neue', sans-serif; font-size: 13px; color: #888; }
  
  h2 { font-family: 'Helvetica Neue', sans-serif; font-size: 18px; font-weight: 700; margin-top: 40px; text-transform: uppercase; letter-spacing: 0.5px; border-left: 3px solid #000; padding-left: 15px; }
  
  .finding { margin-bottom: 30px; }
  .finding-headline { font-weight: 700; font-size: 18px; margin-bottom: 8px; }
  .finding-body { font-size: 16px; color: #333; }
  .finding-meta { font-family: 'Helvetica Neue', sans-serif; font-size: 11px; color: #999; margin-top: 8px; }
  
  .conf-high { color: #059669; font-weight: bold; }
  .conf-med { color: #d97706; font-weight: bold; }

  .footer { margin-top: 60px; border-top: 1px solid #eee; padding-top: 20px; font-family: 'Helvetica Neue', sans-serif; font-size: 11px; color: #aaa; text-align: center; }
</style>
</head>
<body>
  <div class="header">
    <div class="brand">Signl Intelligence</div>
    <div class="title">Competitor Analysis: ${company}</div>
    <div class="meta">Prepared for Akash • ${date}</div>
  </div>

  <p>
    <strong>Executive Summary:</strong> We have detected significant shifts in ${company}'s strategy over the last 90 days. 
    The following intelligence has been triangulated across engineering, market, and social vectors.
  </p>

  <h2>Strategic Developments</h2>

  ${findings.map((f, i) => `
    <div class="finding">
      <div class="finding-headline">${i + 1}. ${f.title}</div>
      <div class="finding-body">${cleanText(f.rawContent)}</div>
      <div class="finding-meta">
        CONFIDENCE: <span class="${f.confidence === 'HIGH' ? 'conf-high' : 'conf-med'}">${f.confidence}</span> 
        // SOURCE: ${f.source}
      </div>
    </div>
  `).join('')}

  <h2>Strategic Recommendations</h2>
  <p>Based on this intelligence, we recommend immediate action on the following:</p>
  <ul>
    <li><strong>Counter-Positioning:</strong> Leverage their recent price hike to capture the SMB market.</li>
    <li><strong>Product Roadmap:</strong> Accelerate the on-prem release; they are ignoring this vector.</li>
  </ul>

  <div class="footer">
    CONFIDENTIAL • GENERATED BY SIGNL v3
  </div>
</body>
</html>
  `;
}

async function testFormatting() {
  console.log("🎨 Testing Email Formatting & JSON Cleaning...");

  // MOCK DATA (Simulating the messy JSON you got)
  const MOCK_FINDINGS = [
    {
      title: "Enterprise Scale Focus",
      confidence: "HIGH",
      source: "EXA",
      rawContent: `{"content":[{"type":"text","text":"The data indicates Pinecone is shifting to enterprise. Key evidence: 1) New 'Contact Sales' only tier. 2) SOC2 Type II announcement."}]}`
    },
    {
      title: "Negative Sentiment on Pricing",
      confidence: "HIGH",
      source: "XAI",
      rawContent: "Users are complaining about a 30% price hike. 'Pinecone used to be cheap, now it is luxury' says @dev_user."
    },
    {
      title: "API Deprecation",
      confidence: "MEDIUM",
      source: "PERPLEXITY",
      rawContent: `{"results": [{"text": "Documentation update: v2 API is deprecated as of Nov 2025. Migration required."}]}`
    }
  ];

  const html = generateHumanReport("Pinecone", MOCK_FINDINGS);

  // Send it
  const sbx = await Sandbox.create('signl-v3-thinking', {
    mcp: {
      resend: { apiKey: process.env.RESEND_API_KEY!, sender: "onboarding@resend.dev", replyTo: "test@test.com" },
      exa: { apiKey: "mock" }, perplexityAsk: { perplexityApiKey: "mock" }, memory: {} // Mock others
    }
  });

  const client = new Client({ name: 'Format-Test', version: '1.0.0' }, { capabilities: {} });
  await client.connect(new StreamableHTTPClientTransport(new URL(sbx.getMcpUrl()), { requestInit: { headers: { 'Authorization': `Bearer ${await sbx.getMcpToken()}` } } }));

  const emailTool = (await client.listTools()).tools.find(t => t.name.includes('send-email') || t.name.includes('send_email'));

  if (emailTool) {
    console.log("💌 Sending formatted email...");
    await client.request(
      {
        method: "tools/call",
        params: {
          name: emailTool.name,
          arguments: {
            to: "thatspacebiker@gmail.com",
            subject: "[TEST] New Format Design",
            html: html,
            text: "Check HTML."
          }
        }
      },
      CallToolResultSchema
    );
    console.log("✅ Sent.");
  }

  await sbx.kill();
}

testFormatting();